# Generated by Django 4.0.10 on 2023-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletinsights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercharacter',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
