# Generated by Django 4.0.10 on 2023-11-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletinsights', '0002_ownercharacter_is_valid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='walletdivision',
            name='division_division_name_idx',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='journals_last_updated',
        ),
        migrations.AddField(
            model_name='walletdivision',
            name='journal_last_updated',
            field=models.DateTimeField(default=None, editable=False, help_text='the last time the journal for this division was updated.', null=True, verbose_name='journal last updated'),
        ),
        migrations.AddIndex(
            model_name='walletdivision',
            index=models.Index(fields=['corp_id', 'division_id', 'division_name'], name='corp_division_id_name_idx'),
        ),
    ]
